set -euo pipefail

# Constants
CONFIG_DIR="/etc/reboot-manager"
CONFIG_FILE="${CONFIG_DIR}/config"
CHECKER_SCRIPT="/usr/local/bin/reboot-checker"
CRON_FILE="/etc/cron.d/reboot-manager"
LOG_FILE="/var/log/reboot-manager.log"

# Helpers
log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
die()  { echo "ERROR: $*" >&2; exit 1; }

usage() {
    cat >&2 << 'EOF'
Usage: sudo /usr/local/reboot-manager set restart <X_days>

  set restart <X_days>   Reboot the machine automatically once uptime reaches
                         X_days whole days. X_days must be an integer >= 1.

Example:
  sudo reboot-manager.sh set restart 7
EOF
    exit 1
}

require_root() {
    [[ "${EUID}" -eq 0 ]] || die "This script must be run with sudo."
}

validate_days() {
    local days="$1"
    [[ "${days}" =~ ^[0-9]+$ ]] || die "X_days must be a positive integer (got: '${days}')."
    [[ "${days}" -ge 1 ]]       || die "X_days must be at least 1."
}

# Write the daily checker
write_checker() {
    cat > "${CHECKER_SCRIPT}" << 'CHECKER'
#!/usr/bin/env bash
# Auto-generated by reboot-manager.sh - do not edit manually.

CONFIG_FILE="/etc/reboot-manager/config"
LOG_FILE="/var/log/reboot-manager.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_FILE}"; }

[[ -f "${CONFIG_FILE}" ]] || { log "Config not found at ${CONFIG_FILE}. Exiting."; exit 1; }
# shellcheck source=/dev/null
source "${CONFIG_FILE}"

# Uptime in whole days (from /proc/uptime, field 1 = seconds since boot)
UPTIME_SECS=$(awk '{print int($1)}' /proc/uptime)
UPTIME_DAYS=$(( UPTIME_SECS / 86400 ))

log "Uptime: ${UPTIME_DAYS} day(s) | Threshold: ${REBOOT_INTERVAL_DAYS} day(s)"

if [[ "${UPTIME_DAYS}" -ge "${REBOOT_INTERVAL_DAYS}" ]]; then
    log "Threshold reached - updating packages and scheduling reboot in 1 minute..."
    # Graceful: broadcast a wall notice before rebooting
    wall "NOTICE: Scheduled reboot triggered by reboot-manager (uptime ${UPTIME_DAYS}d >= ${REBOOT_INTERVAL_DAYS}d). Packages will be updated and the machine will reboot in 1 minute."
    if DEBIAN_FRONTEND=noninteractive apt-get update \
        && DEBIAN_FRONTEND=noninteractive apt-get -y upgrade; then
        log "Packages updated successfully."
    else
        log "Package update failed - rebooting anyway."
    fi
    shutdown -r +1 "Scheduled reboot by reboot-manager"
else
    log "No action needed (${UPTIME_DAYS}d uptime < ${REBOOT_INTERVAL_DAYS}d threshold)."
fi
CHECKER

    chmod +x "${CHECKER_SCRIPT}"
    log "Checker script written to ${CHECKER_SCRIPT}"
}
cmd_set_restart() {
    local days="$1"

    require_root
    validate_days "${days}"

    # 1. Persist config
    mkdir -p "${CONFIG_DIR}"
    cat > "${CONFIG_FILE}" << EOF
# reboot-manager configuration - auto-generated, do not edit manually.
# To change, re-run: sudo reboot-manager.sh set restart <X_days>
REBOOT_INTERVAL_DAYS=${days}
EOF
    chmod 640 "${CONFIG_FILE}"
    log "Config saved: REBOOT_INTERVAL_DAYS=${days}"

    # 2. Write / refresh the checker script
    write_checker

    # 3. Install cron job - runs daily at 03:00
    cat > "${CRON_FILE}" << EOF
# reboot-manager - auto-generated, do not edit manually.
# Checks uptime daily at 03:00 and reboots if threshold is reached.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0 3 * * * root ${CHECKER_SCRIPT}
EOF
    chmod 644 "${CRON_FILE}"
    log "Cron job installed at ${CRON_FILE} (daily check at 03:00)"
 
    # 4. Ensure log file exists and is writable by root
    touch "${LOG_FILE}"
    chmod 640 "${LOG_FILE}"
 
    echo ""
    echo "===================================================="
    echo "| ✓  Auto-restart configured every ${days} day(s)"
    echo "|"
    echo "| Config      : ${CONFIG_FILE}"
    echo "| Checker     : ${CHECKER_SCRIPT}"
    echo "| Cron job    : ${CRON_FILE}"
    echo "| Log         : ${LOG_FILE}"
    echo "===================================================="
}

[[ $# -lt 1 ]] && usage

case "${1}" in
    set)
        [[ $# -eq 3 && "${2}" == "restart" ]] || usage
        cmd_set_restart "${3}"
        ;;
    *)
        usage
                ;;
esac