set -euo pipefail

# Constants
CONFIG_DIR="/etc/reboot-manager"
CONFIG_FILE="${CONFIG_DIR}/config"
CHECKER_SCRIPT="/usr/local/bin/reboot-checker"
CRON_FILE="/etc/cron.d/reboot-manager"
LOG_FILE="/var/log/reboot-manager.log"

# Helpers
log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
die()  { echo "ERROR: $*" >&2; exit 1; }

usage() {
    cat >&2 << 'EOF'
Usage:
  sudo /usr/local/bin/reboot-manager set restart <X_days>
  sudo /usr/local/bin/reboot-manager sysupdate <optin|optout>

  set restart <X_days>   Reboot the machine automatically once uptime reaches
                         X_days whole days. X_days must be an integer >= 1.

  sysupdate optin        Run a full system update (apt-get update + upgrade)
                         before each scheduled reboot. This is the default.
  sysupdate optout       Skip the system update; only reboot.

Examples:
  sudo /usr/local/bin/reboot-manager set restart 7
  sudo /usr/local/bin/reboot-manager sysupdate optout
EOF
    exit 1
}

require_root() {
    [[ "${EUID}" -eq 0 ]] || die "This script must be run with sudo."
}

validate_days() {
    local days="$1"
    [[ "${days}" =~ ^[0-9]+$ ]] || die "X_days must be a positive integer (got: '${days}')."
    [[ "${days}" -ge 1 ]]       || die "X_days must be at least 1."
}

# Config helpers
# Read a key from the config file (empty output if missing).
get_config_value() {
    local key="$1"
    [[ -f "${CONFIG_FILE}" ]] || return 0
    grep -E "^${key}=" "${CONFIG_FILE}" | tail -n1 | cut -d= -f2- || true
}

# Set a key in the config file, adding it if absent. Values are validated
# by callers, so they only ever contain [A-Za-z0-9].
set_config_value() {
    local key="$1" value="$2"
    mkdir -p "${CONFIG_DIR}"
    if [[ ! -f "${CONFIG_FILE}" ]]; then
        cat > "${CONFIG_FILE}" << 'EOF'
# reboot-manager configuration - auto-generated, do not edit manually.
EOF
    fi
    if grep -qE "^${key}=" "${CONFIG_FILE}"; then
        sed -i -E "s/^${key}=.*/${key}=${value}/" "${CONFIG_FILE}"
    else
        echo "${key}=${value}" >> "${CONFIG_FILE}"
    fi
    chmod 640 "${CONFIG_FILE}"
}

# Write the daily checker
write_checker() {
    cat > "${CHECKER_SCRIPT}" << 'CHECKER'
#!/usr/bin/env bash
# Auto-generated by /usr/local/bin/reboot-manager - do not edit manually.

CONFIG_FILE="/etc/reboot-manager/config"
LOG_FILE="/var/log/reboot-manager.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_FILE}"; }

[[ -f "${CONFIG_FILE}" ]] || { log "Config not found at ${CONFIG_FILE}. Exiting."; exit 1; }
# shellcheck source=/dev/null
source "${CONFIG_FILE}"

[[ -n "${REBOOT_INTERVAL_DAYS:-}" ]] || { log "No restart interval configured (run: /usr/local/bin/reboot-manager set restart <X_days>). Exiting."; exit 1; }

# System updates are enabled unless the user explicitly opted out.
SYSTEM_UPDATE="${SYSTEM_UPDATE:-optin}"

# Uptime in whole days (from /proc/uptime, field 1 = seconds since boot)
UPTIME_SECS=$(awk '{print int($1)}' /proc/uptime)
UPTIME_DAYS=$(( UPTIME_SECS / 86400 ))

log "Uptime: ${UPTIME_DAYS} day(s) | Threshold: ${REBOOT_INTERVAL_DAYS} day(s) | System update: ${SYSTEM_UPDATE}"

if [[ "${UPTIME_DAYS}" -ge "${REBOOT_INTERVAL_DAYS}" ]]; then
    if [[ "${SYSTEM_UPDATE}" == "optout" ]]; then
        log "Threshold reached - system update disabled, scheduling reboot in 1 minute..."
        wall "NOTICE: Scheduled reboot triggered by reboot-manager (uptime ${UPTIME_DAYS}d >= ${REBOOT_INTERVAL_DAYS}d). The machine will reboot in 1 minute."
    else
        log "Threshold reached - updating packages and scheduling reboot in 1 minute..."
        # Graceful: broadcast a wall notice before rebooting
        wall "NOTICE: Scheduled reboot triggered by reboot-manager (uptime ${UPTIME_DAYS}d >= ${REBOOT_INTERVAL_DAYS}d). Packages will be updated and the machine will reboot in 1 minute."
        if DEBIAN_FRONTEND=noninteractive apt-get update \
            && DEBIAN_FRONTEND=noninteractive apt-get -y upgrade; then
            log "Packages updated successfully."
        else
            log "Package update failed - rebooting anyway."
        fi
    fi
    shutdown -r +1 "Scheduled reboot by reboot-manager"
else
    log "No action needed (${UPTIME_DAYS}d uptime < ${REBOOT_INTERVAL_DAYS}d threshold)."
fi
CHECKER

    chmod +x "${CHECKER_SCRIPT}"
    log "Checker script written to ${CHECKER_SCRIPT}"
}

cmd_set_restart() {
    local days="$1"

    require_root
    validate_days "${days}"

    # Preserve any existing sysupdate preference (default: optin)
    local sysupdate
    sysupdate="$(get_config_value SYSTEM_UPDATE)"
    sysupdate="${sysupdate:-optin}"

    # 1. Persist config
    mkdir -p "${CONFIG_DIR}"
    cat > "${CONFIG_FILE}" << EOF
# reboot-manager configuration - auto-generated, do not edit manually.
# To change, re-run: sudo /usr/local/bin/reboot-manager set restart <X_days>
#                    sudo /usr/local/bin/reboot-manager sysupdate <optin|optout>
REBOOT_INTERVAL_DAYS=${days}
SYSTEM_UPDATE=${sysupdate}
EOF
    chmod 640 "${CONFIG_FILE}"
    log "Config saved: REBOOT_INTERVAL_DAYS=${days}, SYSTEM_UPDATE=${sysupdate}"

    # 2. Write / refresh the checker script
    write_checker

    # 3. Install cron job - runs daily at 03:00
    cat > "${CRON_FILE}" << EOF
# reboot-manager - auto-generated, do not edit manually.
# Checks uptime daily at 03:00 and reboots if threshold is reached.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0 3 * * * root ${CHECKER_SCRIPT}
EOF
    chmod 644 "${CRON_FILE}"
    log "Cron job installed at ${CRON_FILE} (daily check at 03:00)"

    # 4. Ensure log file exists and is writable by root
    touch "${LOG_FILE}"
    chmod 640 "${LOG_FILE}"

    echo ""
    echo "===================================================="
    echo "| ✓  Auto-restart configured every ${days} day(s)"
    echo "|"
    echo "| System update : ${sysupdate}"
    echo "| Config        : ${CONFIG_FILE}"
    echo "| Checker       : ${CHECKER_SCRIPT}"
    echo "| Cron job      : ${CRON_FILE}"
    echo "| Log           : ${LOG_FILE}"
    echo "===================================================="
}

cmd_sysupdate() {
    local choice="$1"

    require_root
    [[ "${choice}" == "optin" || "${choice}" == "optout" ]] \
        || die "sysupdate expects 'optin' or 'optout' (got: '${choice}')."

    set_config_value SYSTEM_UPDATE "${choice}"
    log "Config saved: SYSTEM_UPDATE=${choice}"

    # Refresh an already-installed checker so older installs pick up this feature
    if [[ -f "${CHECKER_SCRIPT}" ]]; then
        write_checker
    fi

    if [[ "${choice}" == "optin" ]]; then
        echo "✓ Full system update will run before each scheduled reboot."
    else
        echo "✓ System update disabled; the machine will only reboot."
    fi

    if [[ ! -f "${CRON_FILE}" ]]; then
        echo "Note: no restart schedule is set yet. Run: sudo /usr/local/bin/reboot-manager set restart <X_days>"
    fi
}

[[ $# -lt 1 ]] && usage

case "${1}" in
    set)
        [[ $# -eq 3 && "${2}" == "restart" ]] || usage
        cmd_set_restart "${3}"
        ;;
    sysupdate)
        [[ $# -eq 2 ]] || usage
        cmd_sysupdate "${2}"
        ;;
    *)
        usage
        ;;
esac